<?php
/**
 * Copyright © 2015 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @category  Magenest
 */
?>
<?php
$_symbol = $block->getSymbolCurrency()
?>
<div id="total" align="right">
    <font size="5" color="red">New Total</font></br>
    <a1 class="col-Discount">
        <?php /* @escapeNotVerified */ echo __('Discount             :').$_symbol.' '.(float)$block->getDiscount() ?></br>
    </a1>
    <a2 class="col-Subtotal">
        <?php /* @escapeNotVerified */ echo __('Subtotal             :').$_symbol.' '.(float)$block->getSubtotal() ?></br>
    </a2>
    <a3 class="col-Shipping">
        <?php /* @escapeNotVerified */ echo __('Shipping & Handling  :').$_symbol.' '.(float)$block->getShippingHandling() ?></br>
    </a3>
    <a4 class="col-Tax">
        <?php /* @escapeNotVerified */ echo __('Tax  :').$_symbol.' '.(float)$block->getTaxAmount() ?></br>
    </a4>
    <a5 class="col-GrandTotal">
        <b><?php /* @escapeNotVerified */ echo __('Grand Total        :').$_symbol.' '.(float)$block->getGrandTotal() ?></b></br>
    </a5>
</div>
