<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magenest\OrderManager\Block\Address\Shipping\Edit */ ?>
<?php
$_order = $block->getOrder() ;
$status = $_order->getStatus();
?>
<?php if ($block instanceof \Magento\Sales\Block\Order\Info){ $f = 1;}else $f = 0; ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Order Information') ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span></strong>
                <?php if ($status == 'pending'): ?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getViewEditShippingUrl($_order) ?>" class="action view">
                    <span><?php /* @escapeNotVerified */ echo __('Edit') ?></span>
                </a>
                <?php endif; ?>
                <div class="box-content">
                    <address><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getShippingAddress()); ?></address>
                </div>

            </div>

            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Shipping Method') ?></span>
                </strong>
                <div class="box-content">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?php echo $block->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else: ?>
                        <?php /* @escapeNotVerified */ echo __('No shipping information available'); ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Billing Address') ?></span>
            </strong>
            <?php if ($status == 'pending' || $status == 'complete' ): ?>
            <a href="<?php /* @escapeNotVerified */ echo $block->getViewEditBillingUrl($_order) ?>"" class="action view">

                <span><?php /* @escapeNotVerified */ echo __('Edit') ?></span>
            </a>
            <?php endif; ?>
            <div class="box-content">
                <address><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getBillingAddress()); ?></address>
            </div>

        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <?php echo $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
