<?php
/** @var  $block Magenest\OrderManager\Block\Product\AddProduct */
$collections = $block->getDataProduct();
?>


<div class="table-wrapper collection-products">
        <table id="my-collection-products-table" class="data table table-collection-products">
            <caption class="table-caption"><?php echo __('List Product') ?></caption>
            <thead>
            <tr class="heading">
                <th scope="col" class="col id"><?php echo __('ID #') ?></th>
                <th scope="col" class="col product"><?php echo __('Product') ?></th>
                <th scope="col" class="col sku"><?php echo __('SKU') ?></th>
                <th scope="col" class="col price"><?php echo __('Price') ?></th>
                <th scope="col" class="col select"><?php echo __('Select') ?></th>
                <th scope="col" class="col quantity"><?php echo __('Quantity') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php $i = 0 ?>

            <?php foreach ($collections as $collection ) { ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('ID #')) ?>" class="col id">
                        <?php echo  $collection->getId(); ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Product')) ?>" class="col product">
                        <?php echo $collection->getName(); ?>

                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('SKU')) ?>" class="col sku">
                        <?php echo $collection->getSku(); ?>

                    </td>

                    <td data-th="<?php echo $block->escapeHtml(__('Price')) ?>" class="col price">
                        <?php echo $collection->getPrice(); ?>

                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Select')) ?>" class="col select">
                       <a name="check">
                           <input type="checkbox" name="select" value="yes"  style="width: 30px;height: 30px "
                                  />
                       </a>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Quantity')) ?>" class="col quantity">
                        <div class="control">
                            <input type="number" name="quantity" id="quantity" class="input-number-quantity"
                                   style="width: 50px;">
                        </div>

                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="save">
        <button onclick="window.location.href='<?php echo $block->getNewAddProductUrl($collection) ?>'">
            <?php echo __('Add product(s) to order') ?>
        </button>

    </div>
    <?php if ($block->getPagerHtml()): ?>
    <div class="products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
